"""Collection of constants for all api uris"""

# This file was generated by 'export_api_constants.py' at 'https://github.com/johannesgrothe/Smarthome_System'
# Do not modify this file, modify 'api_docs/api_specs.json' export.
# Every change made will be overwritten at next export.

# Write System Config
PATH_CLIENT_SYSTEM_CONFIG_WRITE = "config/system/write"

# Write Event Config
PATH_CLIENT_EVENT_CONFIG_WRITE = "config/event/write"

# Write Gadget Config
PATH_CLIENT_GADGET_CONFIG_WRITE = "config/gadget/write"

# Write Complete Config to Client
PATH_CLIENT_CONFIG_WRITE = "config/write"

# Delete Config
PATH_CLIENT_CONFIG_DELETE = "config/delete"

# Client Heartbeat
PATH_HEARTBEAT = "heartbeat"

# Read Bridge Info
PATH_INFO_BRIDGE = "info/bridge"

# Read Clients Info
PATH_INFO_CLIENTS = "info/clients"

# Read Gadgets Info
PATH_INFO_GADGETS = "info/gadgets"

# Update Gadget
PATH_UPDATE_GADGET = "update/gadget"

# Sync Client
PATH_SYNC_CLIENT = "sync/client"

# Reboot Client
PATH_CLIENT_REBOOT = "reboot/client"

# Client Sync Request
PATH_SYNC_REQUEST = "sync"

# Sync Event
PATH_SYNC_EVENT = "sync/event"

# Test Echo
PATH_TEST_ECHO = "echo"

