"""Collection of constants for all api uris"""

# This file was generated by 'api_constants_exporter.py' at 'https://github.com/johannesgrothe/Smarthome_System'
# Do not modify this file, modify 'api_docs/api_specs.json' and export.
# Every change made will be overwritten at next export.

try:
    from utils.system_identifier import StringSystemIdentifier
    from utils.software_version import SoftwareVersion
except ModuleNotFoundError:
    from .utils.system_identifier import StringSystemIdentifier
    from .utils.software_version import SoftwareVersion


# API Version
api_version = SoftwareVersion(1, 0, 4)


class ApiURIs(StringSystemIdentifier):
    """Container for all API URIs"""

    client_system_config_write = "config/system/write"  # Write System Config
    client_event_config_write = "config/event/write"  # Write Event Config
    client_gadget_config_write = "config/gadget/write"  # Write Gadget Config
    client_config_write = "config/write"  # Write Complete Config to Client
    client_config_delete = "config/delete"  # Delete Config
    heartbeat = "heartbeat"  # Client Heartbeat
    info_bridge = "info/bridge"  # Read Bridge Info
    info_clients = "info/clients"  # Read Clients Info
    info_gadgets = "info/gadgets"  # Read Gadgets Info
    update_gadget = "update/gadget"  # Update Gadget
    sync_client = "sync/client"  # Sync Client
    client_reboot = "reboot/client"  # Reboot Client
    sync_request = "sync"  # Client Sync Request
    sync_event = "sync/event"  # Sync Event
    test_echo = "echo"  # Test Echo
    config_storage_get_all = "config/storage/get_all"  # Retrieve all stored configs
    config_storage_get = "config/storage/get"  # Retrieve stored config
    config_storage_save = "config/storage/save"  # Save config
    config_storage_delete = "config/storage/delete"  # Delete Config
    bridge_update_check = "bridge/update/check"  # Bridge update check
    bridge_update_execute = "bridge/update/execute"  # Bridge update execute

