#pragma once
// Collection of constants for all api uris

// This file was generated by 'api_constants_exporter.py' at 'https://github.com/johannesgrothe/Smarthome_System'
// Do not modify this file, modify 'api_docs/api_specs.json' and export.
// Every change made will be overwritten at next export.

#include <string>
#include <cstdint>

// Namespace for all api constants and definitions
namespace api_definitions {

    // API Version
    namespace version {
        constexpr uint8_t major = 1;
        constexpr uint8_t minor = 0;
        constexpr uint8_t bugfix = 6;
    }

    // Api URIs
    namespace uris {
        constexpr char heartbeat [] = "heartbeat";  // Client Heartbeat
        constexpr char update_gadget [] = "update/gadget";  // Update Gadget
        constexpr char sync_client [] = "sync/client";  // Sync Client
        constexpr char sync_event [] = "sync/event";  // Sync Event
        constexpr char update_gadget [] = "update/gadget";  // Update Gadget
        constexpr char sync_client [] = "sync/client";  // Sync Client
        constexpr char sync_event [] = "sync/event";  // Sync Event
    }
}
