// Collection of constants for all api uris

// This file was generated by 'export_api_constants.py' at 'https://github.com/johannesgrothe/Smarthome_System'
// Do not modify this file, modify 'api_docs/api_specs.json' export.
// Every change made will be overwritten at next export.

// Write System Config
#define PATH_CLIENT_SYSTEM_CONFIG_WRITE "config/system/write"

// Write Event Config
#define PATH_CLIENT_EVENT_CONFIG_WRITE "config/event/write"

// Write Gadget Config
#define PATH_CLIENT_GADGET_CONFIG_WRITE "config/gadget/write"

// Write Complete Config to Client
#define PATH_CLIENT_CONFIG_WRITE "config/write"

// Delete Config
#define PATH_CLIENT_CONFIG_DELETE "config/delete"

// Client Heartbeat
#define PATH_HEARTBEAT "heartbeat"

// Read Bridge Info
#define PATH_INFO_BRIDGE "info/bridge"

// Read Clients Info
#define PATH_INFO_CLIENTS "info/clients"

// Read Gadgets Info
#define PATH_INFO_GADGETS "info/gadgets"

// Sync Gadget
#define PATH_SYNC_GADGET "sync/gadget"

// Update Gadget
#define PATH_UPDATE_GADGET "update/gadget"

// Sync Client
#define PATH_SYNC_CLIENT "sync/client"

