"""Collection of constants for all gadgets"""

# This file was generated by 'constants_exporter_gadgets_python.py' at 'https://github.com/johannesgrothe/Smarthome_System'
# Do not modify this file, modify 'api_docs/api_specs.json' and 'gadget_docs/gadget_specs.json' and export.
# Every change made will be overwritten at next export.

import enum


class RemoteGadgetIdentifier(enum.IntEnum):
    """Gadgets running on the ESP clients (remote gadgets)"""

    unknown = 0  # Unknown Gadget / Error Case
    custom = 1  # Custom Gadget
    lamp_neopixel_rgb_basic = 2  # NeoPixel Basic RGB Lamp
    lamp_basic = 3  # Basic Lamp
    fan_westinghouse_ir = 4  # Westinghouse IR Fan
    lamp_westinghouse_ir = 5  # Westinghouse IR Fan Lamp
    doorbell_basic = 6  # Doorbell Basic
    wallswitch_basic = 9  # Basic Wallswitch
    sensor_motion_hr501 = 10  # HR501 Motion Sensor
    sensor_temperature_dht = 11  # DHT Temperature/Humidity Sensor


class LocalGadgetIdentifier(enum.IntEnum):
    """Gadgets running on the bridge itself (local gadget)"""

    denon_av_receiver = 0  # Denon AV Receiver


class GadgetClass(enum.IntEnum):
    """General categories of gadgets. Two gadgets of the same class have the same attributes but may differ in implemetation"""

    unknown = 0  # Unknown
    lamp = 1  # Lamp
    lamp_adjustable = 2  # Adjustable Lamp
    lamp_rgb = 3  # RGB Lamp
    fan = 4  # Fan
    tv = 5  # TV
    media_player = 6  # Media Player
    hum_sensor = 7  # Humidity Sensor
    temp_sensor = 8  # Temperature Sensor
    hum_temp_sensor = 9  # Humidity + Temperature Sensor
    mov_sensor = 10  # Movement Sensor
    doorbell = 11  # Doorbell
    stateless_switch = 12  # Stateless Switch
    state_switch = 13  # Switch


GadgetClassMapping = {
    GadgetClass.unknown: [RemoteGadgetIdentifier.unknown, RemoteGadgetIdentifier.custom],
    GadgetClass.lamp: [RemoteGadgetIdentifier.lamp_basic, RemoteGadgetIdentifier.lamp_westinghouse_ir],
    GadgetClass.lamp_adjustable: [],
    GadgetClass.lamp_rgb: [RemoteGadgetIdentifier.lamp_neopixel_rgb_basic],
    GadgetClass.fan: [LocalGadgetIdentifier.denon_av_receiver, RemoteGadgetIdentifier.fan_westinghouse_ir],
    GadgetClass.tv: [],
    GadgetClass.media_player: [],
    GadgetClass.hum_sensor: [],
    GadgetClass.temp_sensor: [],
    GadgetClass.hum_temp_sensor: [RemoteGadgetIdentifier.sensor_temperature_dht],
    GadgetClass.mov_sensor: [RemoteGadgetIdentifier.sensor_motion_hr501],
    GadgetClass.doorbell: [RemoteGadgetIdentifier.doorbell_basic, RemoteGadgetIdentifier.wallswitch_basic],
    GadgetClass.stateless_switch: [],
    GadgetClass.state_switch: []
}
