// Collection of constants for all gadgets

// This file was generated by 'constants_exporter_gadgets_js.py' at 'https://github.com/johannesgrothe/Smarthome_System'
// Do not modify this file, modify 'api_docs/api_specs.json' and 'gadget_docs/gadget_specs.json' and export.
// Every change made will be overwritten at next export.


// CLass for all gadget and characteristic definitions
export default class GadgetDefinitions {

    // Count of the different gadget identifiers
    static GadgetIdentifierCount = 10;

    // Gadget Identifier
    static gadget_unknown = 0;  // Unknown Gadget / Error Case
    static gadget_custom = 1;  // Custom Gadget
    static gadget_lamp_neopixel_rgb_basic = 2;  // NeoPixel Basic RGB Lamp
    static gadget_lamp_basic = 3;  // Basic Lamp
    static gadget_fan_westinghouse_ir = 4;  // Westinghouse IR Fan
    static gadget_lamp_westinghouse_ir = 5;  // Westinghouse IR Fan Lamp
    static gadget_doorbell_basic = 6;  // Doorbell Basic
    static gadget_wallswitch_basic = 9;  // Basic Wallswitch
    static gadget_sensor_motion_hr501 = 10;  // HR501 Motion Sensor
    static gadget_sensor_temperature_dht = 11;  // DHT Temperature/Humidity Sensor
}
