#pragma once
// Collection of constants for all gadgets

// This file was generated by 'constants_exporter_gadgets_cpp.py' at 'https://github.com/johannesgrothe/Smarthome_System'
// Do not modify this file, modify 'api_docs/api_specs.json' and 'gadget_docs/gadget_specs.json' and export.
// Every change made will be overwritten at next export.

#include <cstdint>

// Namespace for all gadget and characteristic definitions
namespace gadget_definitions {

    // Count of the different gadget identifiers
    constexpr uint8_t GadgetIdentifierCount = 10;

    // Gadgets running on the ESP clients (remote gadgets)
    enum class GadgetIdentifier {
        unknown = 0,  // Unknown Gadget / Error Case
        custom = 1,  // Custom Gadget
        lamp_neopixel_rgb_basic = 2,  // NeoPixel Basic RGB Lamp
        lamp_basic = 3,  // Basic Lamp
        fan_westinghouse_ir = 4,  // Westinghouse IR Fan
        lamp_westinghouse_ir = 5,  // Westinghouse IR Fan Lamp
        doorbell_basic = 6,  // Doorbell Basic
        wallswitch_basic = 9,  // Basic Wallswitch
        sensor_motion_hr501 = 10,  // HR501 Motion Sensor
        sensor_temperature_dht = 11  // DHT Temperature/Humidity Sensor
    };
}
