#pragma once
// Collection of constants for all gadgets and characteristics

// This file was generated by 'gadget_constants_exporter.py' at 'https://github.com/johannesgrothe/Smarthome_System'
// Do not modify this file, modify 'gadget_docs/gadget_specs.json' and export.
// Every change made will be overwritten at next export.

