#pragma once
// Collection of constants for all variants

// This file was generated by 'constants_exporter_variants_cpp.py' at 'https://github.com/johannesgrothe/Smarthome_System'
// Do not modify this file, modify 'api_docs/api_specs.json' and 'gadget_docs/gadget_specs.json' and export.
// Every change made will be overwritten at next export.


// Hardware Variants
enum class HwVariant {
    unknown = 1,  // Element representing any error case
    single_port = 2  // Simple controller setup with a single port exposed
};

// Software Variants
enum class SwVariant {
    unknown = 1,  // Element representing any error case
    single_neopixel = 2  // Just single neopixel gadget
};
