import os

# C++
CPP_NAMESPACE_API_DOCS = "api_definitions"
CPP_NAMESPACE_API_URIS = "uris"
CPP_NAMESPACE_API_VERSION = "version"
CPP_NAMESPACE_GADGET_DOCS = "gadget_definitions"

# Python
PY_CLASSNAME_URIS = "ApiURIs"
PY_CLASSNAME_URIS_SUPER = "ApiURIsSuper"
PY_CLASSNAME_ACCESS_LEVEL = "ApiAccessLevel"
PY_CLASSNAME_ACCESS_TYPE_SUPER = "ApiAccessLevelSuper"
PY_CLASSNAME_ENDPOINT_TYPE = "ApiEndpointCategory"
PY_CLASSNAME_ENDPOINT_TYPE_SUPER = "ApiEndpointCategorySuper"
PY_CLASSNAME_ACCESS_TYPE = "ApiAccessType"
PY_CLASSNAME_API_DEFINITION_CONTAINER = "ApiEndpointDefinition"
PY_CLASSNAME_ACCESS_LEVEL_MAPPING = "ApiAccessLevelMapping"
PY_VARNAME_API_VERSION = "api_version"
PY_CLASSNAME_GADGET_IDENTIFIER_REMOTE = "RemoteGadgetIdentifier"
PY_CLASSNAME_GADGET_IDENTIFIER_LOCAL = "LocalGadgetIdentifier"
PY_VARNAME_GADGET_CLASS_MAPPING = "GadgetClassMapping"
PY_CLASSNAME_GADGET_CLASS = "GadgetClass"


# JavaScript
JS_CLASSNAME_GADGET_SPECS = "GadgetDefinitions"
JS_CLASSNAME_API = "ApiConstants"

# Swift
SWIFT_CLASSNAME_API_VERSION = "SoftwareVersion"
SWIFT_VARNAME_API_VERSION = "api_version"
SWIFT_CLASSNAME_URIS = "ApiURIs"
