name: Repository Checks

on: [ pull_request ]

jobs:
  semi_linear_history_check:

    name: Check Semi-Linear History

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Check Semi-Linear History
        run: git merge-base --is-ancestor origin/"${{ github.event.repository.default_branch }}" HEAD
